apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-selector
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
  nodeSelector:
    nodetype: edge
    name: edge-node-1
