apiVersion: v1
kind: Pod
metadata:
  name: postgresql-antipod-mysql
  labels:
    app: postgresql
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mysql
        topologyKey: kubernetes.io/hostname
  containers:
  - name: postgresql
    image: postgres:latest
    env:
    - name:  POSTGRES_PASSWORD
      value: password

