apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-rollingupdate-deployment
  labels:
    app: grafana
spec:
  replicas: 10
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    minReadySecond: 10
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
