apiVersion: v1
kind: Pod
metadata:
  name: grafana-node-affinity
  labels:
    app: grafana
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nodetype
            operator: In
            values:
            - edge
  containers:
  - name: grafana
    image: grafana/grafana
