apiVersion: v1
kind: Service
metadata:
  name: nginx-multiport-service
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 80
  - name: https
    protocol: TCP
    port: 3001
    targetPort: 443
