apiVersion: v1
kind: Pod
metadata:
  name: grafana-node-16.04
  labels:
    app: grafana
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: os.version
            operator: In
            values:
            - "16.04"
  containers:
  - name: grafana
    image: grafana/grafana
