apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: pv001
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: pv-claim
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs-k8s
    server: 192.168.1.41
