apiVersion: v1
kind: Pod
metadata:
  name: grafana-pod-mysql
  labels:
    app: grafana
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mysql
        topologyKey: kubernetes.io/hostname
    podAntiAffinity: 
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - mongodb
          topologyKey: kubernetes.io/hostname
  containers:
  - name: grafana
    image: grafana/grafana
