apiVersion: v1
kind: Pod
metadata:
  name: grafana-pod-mongodb
  labels:
    app: grafana
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mongodb
        topologyKey: kubernetes.io/hostname  
  containers:
  - name: grafana
    image: grafana/grafana
